"""Fork the global brainstem kernel into a project-specific brainstem instance.

Copies brainstem.py + sibling kernel files verbatim from the global install at
~/.brainstem/src/rapp_brainstem into <project_path>/.brainstem/src/rapp_brainstem.
Auto-picks a free port, writes a project .env, preserves any existing project
soul.md and agents/ files. Registers the result in ~/.brainstem/projects.json
so future forks can see what ports are taken.

The kernel itself is never edited — projects differ via .env (PORT, AGENTS_PATH,
SOUL_PATH) and their own agents/ + soul.md.
"""
import hashlib
import json
import os
import re
import shutil
import socket
from datetime import datetime, timezone
from pathlib import Path

from agents.basic_agent import BasicAgent


KERNEL_FILES = [
    "brainstem.py",
    "local_storage.py",
    "requirements.txt",
    "start.sh",
    "start.ps1",
    "index.html",
    "VERSION",
]
AGENT_HELPERS = ["basic_agent.py"]
PRESERVE_IF_EXISTS = ["soul.md", ".env"]
AUTH_FILES = [".copilot_token", ".copilot_session"]
ENV_KEYS_TO_INHERIT = ["GITHUB_TOKEN", "GITHUB_MODEL", "VOICE_ZIP_PASSWORD", "TEAMS_CHANNEL_EMAIL"]
PROJECTS_REGISTRY = Path.home() / ".brainstem" / "projects.json"
DEFAULT_PORT_FLOOR = 7073


def _global_brainstem_dir() -> Path:
    # this file lives at <global>/agents/brainstem_fork_agent.py
    return Path(__file__).resolve().parent.parent


def _port_is_free(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            s.bind(("127.0.0.1", port))
        except OSError:
            return False
    return True


def _pick_port(floor: int, taken: set) -> int:
    port = floor
    while port < 7200:
        if port not in taken and _port_is_free(port):
            return port
        port += 1
    raise RuntimeError(f"no free port found in [{floor}, 7200)")


def _read_env(path: Path) -> dict:
    env = {}
    if not path.exists():
        return env
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        env[k.strip()] = v.strip()
    return env


def _write_env(path: Path, env: dict) -> None:
    lines = [
        "# Generated by BrainstemFork agent",
        "# Brainstem kernel + agents discovery are env-driven; edit values, never the kernel.",
        "",
    ]
    for k in ["GITHUB_TOKEN", "GITHUB_MODEL", "SOUL_PATH", "AGENTS_PATH", "PORT", "VOICE_ZIP_PASSWORD", "TEAMS_CHANNEL_EMAIL"]:
        if k in env:
            lines.append(f"{k}={env[k]}")
    path.write_text("\n".join(lines) + "\n")


def _load_registry() -> dict:
    if not PROJECTS_REGISTRY.exists():
        return {"projects": []}
    try:
        return json.loads(PROJECTS_REGISTRY.read_text())
    except (json.JSONDecodeError, OSError):
        return {"projects": []}


def _save_registry(reg: dict) -> None:
    PROJECTS_REGISTRY.parent.mkdir(parents=True, exist_ok=True)
    PROJECTS_REGISTRY.write_text(json.dumps(reg, indent=2))


_AGENT_NAME_RE = re.compile(r"""self\.name\s*=\s*['"]([^'"]+)['"]""")
_AGENT_DESC_RE = re.compile(r"""['"]description['"]\s*:\s*\(?\s*['"]([^'"]+)['"]""")


def _parse_agent_meta(filepath: Path) -> tuple:
    """Return (name, description) parsed from an agent file. Falls back to filename."""
    fallback_name = filepath.stem.replace("_agent", "").replace("_", " ").title().replace(" ", "")
    try:
        src = filepath.read_text(errors="replace")
    except OSError:
        return fallback_name, ""
    name_m = _AGENT_NAME_RE.search(src)
    desc_m = _AGENT_DESC_RE.search(src)
    return (
        name_m.group(1) if name_m else fallback_name,
        desc_m.group(1) if desc_m else "",
    )


def _project_id(project_path: str) -> str:
    """Deterministic short id derived from absolute project path (upsert-stable)."""
    h = hashlib.sha1(project_path.encode("utf-8")).hexdigest()[:12]
    return f"brainstem-{h}"


def _build_tracker_export(project_root: Path, target_dir: Path, port: int, agents_dir: Path, copilot_ok: bool) -> dict:
    """Build a payload matching the localfirst project tracker schema (projectTrackerData)."""
    now = datetime.now(timezone.utc).isoformat()
    pid = _project_id(str(project_root))

    custom_agents = []
    agent_names = []
    if agents_dir.exists():
        for f in sorted(agents_dir.glob("*_agent.py")):
            if f.name == "basic_agent.py":
                continue
            name, desc = _parse_agent_meta(f)
            if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*", name):
                continue
            agent_names.append(name)
            custom_agents.append({
                "name": name,
                "description": desc or f"Project agent at {f.name}",
                "category": "brainstem",
                "status": "new",
            })

    project = {
        "id": pid,
        "customerName": project_root.name,
        "type": "Brainstem Fork",
        "status": "active",
        "description": (
            f"Project-specific RAPP brainstem forked from the global kernel at "
            f"~/.brainstem/src/rapp_brainstem. Lives at {target_dir}. "
            f"Copilot auth: {'inherited' if copilot_ok else 'not configured'}."
        ),
        "stakeholders": "",
        "competingSolution": "",
        "contractDetails": "",
        "mvpUseCase": f"Local brainstem running at http://localhost:{port}",
        "mvpTimeline": "",
        "agents": agent_names,
        "createdDate": now,
        "updatedDate": now,
    }

    timeline_event = {
        "date": now,
        "title": f"Brainstem forked: {project_root.name}",
        "description": f"Forked global kernel into {target_dir} on port {port}.",
    }

    return {
        "projects": [project],
        "agents": {"builtin": [], "custom": custom_agents},
        "timeline": [timeline_event],
        "exportDate": now,
    }


def _upsert_project(reg: dict, project_path: str, target: str, port: int) -> None:
    now = datetime.now(timezone.utc).isoformat()
    for p in reg["projects"]:
        if p.get("project_path") == project_path:
            p.update({"target": target, "port": port, "updated": now})
            return
    reg["projects"].append({
        "project_path": project_path,
        "target": target,
        "port": port,
        "created": now,
        "updated": now,
    })


class BrainstemForkAgent(BasicAgent):
    def __init__(self):
        self.name = "BrainstemFork"
        self.metadata = {
            "name": self.name,
            "description": (
                "Fork the global brainstem kernel into a project-specific brainstem instance. "
                "Copies brainstem.py and sibling kernel files from ~/.brainstem/src/rapp_brainstem into "
                "<project_path>/.brainstem/src/rapp_brainstem, picks a free port, writes a project .env, "
                "and preserves any existing soul.md and agents/. Use when the user wants to set up or "
                "refresh a project-specific brainstem alongside the global one."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "project_path": {
                        "type": "string",
                        "description": "Absolute path to the project root. The forked brainstem will be created at <project_path>/.brainstem/src/rapp_brainstem.",
                    },
                    "port": {
                        "type": "integer",
                        "description": "Optional port for the project brainstem. If omitted, auto-picks the next free port starting at 7073.",
                    },
                    "replace_env": {
                        "type": "boolean",
                        "description": "If true, regenerate the project .env even if it already exists. Default false.",
                    },
                    "force_soul": {
                        "type": "boolean",
                        "description": "If true, overwrite the project soul.md with the global one. Default false (preserve project soul).",
                    },
                    "include_auth": {
                        "type": "boolean",
                        "description": "If true (default), copy .copilot_token and .copilot_session from global so the forked brainstem is immediately usable without re-auth.",
                    },
                    "emit_tracker_export": {
                        "type": "boolean",
                        "description": "If true (default), also write a projectTrackerData-shaped JSON file (project_tracker_export.json) into the project brainstem dir. Mergeable into the localfirst project tracker tool.",
                    },
                    "tracker_out": {
                        "type": "string",
                        "description": "Optional override path for the tracker export JSON. Default: <target>/project_tracker_export.json.",
                    },
                },
                "required": ["project_path"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        project_path = kwargs.get("project_path", "").strip()
        if not project_path:
            return json.dumps({"error": "project_path is required"})

        project_root = Path(project_path).expanduser().resolve()
        if not project_root.exists() or not project_root.is_dir():
            return json.dumps({"error": f"project_path does not exist or is not a directory: {project_root}"})

        global_dir = _global_brainstem_dir()
        target_dir = project_root / ".brainstem" / "src" / "rapp_brainstem"
        target_agents = target_dir / "agents"
        target_agents.mkdir(parents=True, exist_ok=True)

        # Pick port (avoiding ports the global brainstem AND the registry know about)
        registry = _load_registry()
        taken = {p["port"] for p in registry["projects"] if p.get("project_path") != str(project_root)}
        # also avoid the global brainstem's own port
        global_env = _read_env(global_dir / ".env")
        try:
            taken.add(int(global_env.get("PORT", 7071)))
        except (TypeError, ValueError):
            taken.add(7071)
        port = kwargs.get("port")
        if port is None:
            port = _pick_port(DEFAULT_PORT_FLOOR, taken)
        else:
            port = int(port)

        # Copy kernel files (always overwrite — kernel is sacred but interchangeable)
        copied, missing = [], []
        for fname in KERNEL_FILES:
            src = global_dir / fname
            if not src.exists():
                missing.append(fname)
                continue
            dst = target_dir / fname
            shutil.copy2(src, dst)
            copied.append(fname)

        # Agent helpers (always copy — required for any project agent to import)
        for fname in AGENT_HELPERS:
            src = global_dir / "agents" / fname
            if src.exists():
                shutil.copy2(src, target_agents / fname)
                copied.append(f"agents/{fname}")

        # Preserve project soul.md unless force_soul=True
        preserved = []
        force_soul = bool(kwargs.get("force_soul", False))
        target_soul = target_dir / "soul.md"
        if target_soul.exists() and not force_soul:
            preserved.append("soul.md")
        else:
            global_soul = global_dir / "soul.md"
            if global_soul.exists():
                shutil.copy2(global_soul, target_soul)
                copied.append("soul.md")

        # Generate / preserve project .env
        replace_env = bool(kwargs.get("replace_env", False))
        target_env = target_dir / ".env"
        if target_env.exists() and not replace_env:
            existing = _read_env(target_env)
            existing["PORT"] = str(port)
            existing.setdefault("SOUL_PATH", "./soul.md")
            existing.setdefault("AGENTS_PATH", "./agents")
            _write_env(target_env, existing)
            preserved.append(".env (port updated)")
        else:
            env = {
                "SOUL_PATH": "./soul.md",
                "AGENTS_PATH": "./agents",
                "PORT": str(port),
            }
            for k in ENV_KEYS_TO_INHERIT:
                if k in global_env:
                    env[k] = global_env[k]
            _write_env(target_env, env)
            copied.append(".env")

        # Inherit Copilot auth state so the forked brainstem is immediately usable
        include_auth = bool(kwargs.get("include_auth", True))
        auth_copied = []
        if include_auth:
            for fname in AUTH_FILES:
                src = global_dir / fname
                dst = target_dir / fname
                if src.exists() and not dst.exists():
                    shutil.copy2(src, dst)
                    auth_copied.append(fname)
                elif dst.exists():
                    preserved.append(fname)

        # Register the project in ~/.brainstem/projects.json
        _upsert_project(registry, str(project_root), str(target_dir), port)
        _save_registry(registry)

        # Tracker export — JSON sidecar conforming to projectTrackerData schema
        tracker_export = None
        tracker_out_path = None
        if bool(kwargs.get("emit_tracker_export", True)):
            tracker_export = _build_tracker_export(
                project_root=project_root,
                target_dir=target_dir,
                port=port,
                agents_dir=target_agents,
                copilot_ok=bool(auth_copied) or any(f.startswith(".copilot") for f in preserved),
            )
            tracker_out_path = Path(kwargs.get("tracker_out") or (target_dir / "project_tracker_export.json"))
            tracker_out_path.parent.mkdir(parents=True, exist_ok=True)
            tracker_out_path.write_text(json.dumps(tracker_export, indent=2))

        start_cmd = f"cd {target_dir} && ./start.sh"

        result = {
            "ok": True,
            "global_brainstem": str(global_dir),
            "project_brainstem": str(target_dir),
            "port": port,
            "url": f"http://localhost:{port}",
            "copied": copied,
            "auth_copied": auth_copied,
            "preserved": preserved,
            "missing_in_global": missing,
            "registry": str(PROJECTS_REGISTRY),
            "start_command": start_cmd,
            "tracker_export_path": str(tracker_out_path) if tracker_out_path else None,
            "tracker_export": tracker_export,
        }
        return json.dumps(result, indent=2)
