#!/usr/bin/env python3
"""
build-momentfactory.py — collapse the 8 MomentFactory source files into
ONE sacred deployable agent.py.

Reads:
    agents/sensorium_agent.py
    agents/significance_filter_agent.py
    agents/hook_writer_agent.py
    agents/body_writer_agent.py
    agents/channel_router_agent.py
    agents/card_forger_agent.py
    agents/seed_stamper_agent.py        (pure function, no LLM)
    agents/moment_factory_agent.py      (top-level composite)

Writes:
    agents/momentfactory_agent.py — ONE drop-in file.

Mechanics: extract every SOUL constant + the WORDS wordlist + the CHANNELS
list, rename leaf classes to _Internal*, rewrite composite instantiations,
inline ONE _llm_call + _post helper at the bottom, expose a single public
MomentFactory entrypoint with a MomentFactoryAgent alias for brainstem
discovery.
"""
from __future__ import annotations
import re
import ast
from pathlib import Path

RAPP_DIR = Path(__file__).resolve().parent.parent          # rapp_store/momentfactory/
AGENTS   = RAPP_DIR / "source"                             # multi-file source
OUT_DIR  = RAPP_DIR / "singleton"
OUT_DIR.mkdir(exist_ok=True)
OUT      = OUT_DIR / "momentfactory_agent.py"

LEAVES_WITH_SOUL = [
    ("sensorium_agent.py",          "SENSORIUM"),
    ("significance_filter_agent.py","SIGNIFICANCE"),
    ("hook_writer_agent.py",        "HOOK"),
    ("body_writer_agent.py",        "BODY"),
    ("channel_router_agent.py",     "CHANNEL_ROUTER"),
    ("card_forger_agent.py",        "CARD_FORGER"),
]
LEAF_NO_LLM = "seed_stamper_agent.py"
COMPOSITE   = "moment_factory_agent.py"

# Class renames so the brainstem's *Agent discovery only sees MomentFactoryAgent
RENAMES = {
    "SensoriumAgent":           "_InternalSensorium",
    "SignificanceFilterAgent":  "_InternalSignificanceFilter",
    "HookWriterAgent":          "_InternalHookWriter",
    "BodyWriterAgent":          "_InternalBodyWriter",
    "ChannelRouterAgent":       "_InternalChannelRouter",
    "CardForgerAgent":          "_InternalCardForger",
    "SeedStamperAgent":         "_InternalSeedStamper",
}


def parse(path: Path):
    src = path.read_text()
    return ast.parse(src), src


def get_assigns(mod, src, name):
    out = []
    for node in mod.body:
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == name:
                    out.append(ast.get_source_segment(src, node))
    return out


def get_class_src(mod, src, class_name):
    for node in mod.body:
        if isinstance(node, ast.ClassDef) and node.name == class_name:
            return ast.get_source_segment(src, node)
    return None


def get_assert_src(mod, src):
    """Return all top-level Assert source segments (for the WORDS sanity check)."""
    out = []
    for node in mod.body:
        if isinstance(node, ast.Assert):
            out.append(ast.get_source_segment(src, node))
    return out


# ── Build the singleton ───────────────────────────────────────────────

OUT_SRC = '''"""
momentfactory_agent.py — the deployable MomentFactory singleton.

ONE sacred agent.py file containing the entire converged moment-to-Drop
pipeline. Drop it into any RAPP brainstem's agents/ directory and it works.

This file is generated by tools/build-momentfactory.py from the multi-file
source under agents/. The multi-file form is editable and iterable (the
double-jump loop runs against it). This singleton is the SHIP-TIME artifact:
no sibling-import dependencies, no helper modules, no repo layout
assumptions. Just BasicAgent + an LLM key in the environment, and the public
MomentFactory.perform(source, source_type, ...) → Drop.

Inlined personas (sacred SOULs preserved verbatim):
  - Sensorium               (normalize raw moment)
  - SignificanceFilter      (refuse low-significance moments — surprise specialist)
  - HookWriter              (1 sentence)
  - BodyWriter              (3-5 sentences)
  - ChannelRouter           (pick a Subrappter)
  - CardForger              (mint a RAR-compatible card)
  - SeedStamper             (deterministic 64-bit seed + 7-word incantation; NO LLM)

Public entrypoint: the MomentFactory class. Every internal class is prefixed
with _Internal so the brainstem's *Agent discovery exposes only MomentFactory
(via the MomentFactoryAgent alias at the bottom).

Generated from:
'''
for fn, _ in LEAVES_WITH_SOUL:
    OUT_SRC += f'  - agents/{fn}\n'
OUT_SRC += f'  - agents/{LEAF_NO_LLM}\n'
OUT_SRC += f'  - agents/{COMPOSITE}\n'
OUT_SRC += '"""\n\n'

OUT_SRC += '''from agents.basic_agent import BasicAgent
import json
import re
import os
import hashlib
import urllib.request
import urllib.error


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/moment-factory-singleton",
    "tier": "core",
    "trust": "community",
    "version": "0.1.0",
    "tags": ["composite", "moment-pipeline", "rapplication", "rappterbook-engine", "singleton"],
    "delegates_to_inlined": [
        "@rapp/sensorium",
        "@rapp/significance-filter",
        "@rapp/hook-writer",
        "@rapp/body-writer",
        "@rapp/channel-router",
        "@rapp/card-forger",
        "@rapp/seed-stamper",
    ],
    "example_call": {"args": {"source": "git commit hash + diff + msg",
                              "source_type": "code-commit"}},
}


SHIP_THRESHOLD = 0.5


# ─── Wordlist for the 7-word incantation (256 unique words) ───────────

'''

# Pull the WORDS constant + its assertion verbatim from seed_stamper_agent.py
mod, src = parse(AGENTS / LEAF_NO_LLM)
words_assigns = get_assigns(mod, src, "WORDS")
words_asserts = get_assert_src(mod, src)
OUT_SRC += "\n".join(words_assigns) + "\n"
for a in words_asserts:
    OUT_SRC += a + "\n"
OUT_SRC += "\n\n"

# ─── ChannelRouter's CHANNELS list — emitted FIRST so SOULs that f-string
#     it (CHANNEL_ROUTER SOUL) resolve at import time.

mod, src = parse(AGENTS / "channel_router_agent.py")
channels_assigns = get_assigns(mod, src, "CHANNELS")
if channels_assigns:
    OUT_SRC += "# ─── ChannelRouter's canonical channel set ────────────────────────────\n\n"
    OUT_SRC += channels_assigns[0] + "\n\n"

# ─── SOUL constants from each LLM-using leaf ──────────────────────────

OUT_SRC += "# ─── SOUL constants (verbatim from each leaf agent.py) ────────────────\n\n"
for fn, short in LEAVES_WITH_SOUL:
    mod, src = parse(AGENTS / fn)
    soul_segs = get_assigns(mod, src, "SOUL")
    if not soul_segs:
        raise RuntimeError(f"no SOUL in {fn}")
    renamed = re.sub(r'^SOUL\s*=', f'_SOUL_{short} =', soul_segs[0])
    OUT_SRC += renamed + "\n\n"

# ─── _safe_json helper from the composite ─────────────────────────────

OUT_SRC += "\n# ─── Helpers ───────────────────────────────────────────────────────────\n\n"
mod, src = parse(AGENTS / COMPOSITE)
for node in mod.body:
    if isinstance(node, ast.FunctionDef) and node.name == "_safe_json":
        OUT_SRC += ast.get_source_segment(src, node) + "\n\n"
        break

# ─── Internal leaf classes (renamed, SOUL refs rewritten) ─────────────

OUT_SRC += "\n# ─── Internal persona classes (prefixed _Internal) ─────────────────────\n\n"

def rewrite_leaf_class(class_src: str, original_name: str, soul_ref: str | None) -> str:
    new = class_src
    # Rename class
    new_name = RENAMES[original_name]
    new = re.sub(rf'\bclass {re.escape(original_name)}\b', f'class {new_name[6:].rjust(0)}', new)  # tmp
    new = re.sub(rf'\bclass {re.escape(original_name)}\b', f'class {new_name}', class_src)
    # Replace SOUL reference (only present in LLM-using leaves)
    if soul_ref:
        new = re.sub(r'\bSOUL\b', soul_ref, new)
    return new

for fn, short in LEAVES_WITH_SOUL:
    mod, src = parse(AGENTS / fn)
    original_class = next(c for c in RENAMES if c.replace("Agent","").lower() == fn.replace("_agent.py","").replace("_","").lower())
    cls_src = get_class_src(mod, src, original_class)
    if not cls_src:
        raise RuntimeError(f"could not find class {original_class} in {fn}")
    OUT_SRC += rewrite_leaf_class(cls_src, original_class, f"_SOUL_{short}") + "\n\n"

# SeedStamper is a pure function — no SOUL reference rewrite needed
mod, src = parse(AGENTS / LEAF_NO_LLM)
ss_src = get_class_src(mod, src, "SeedStamperAgent")
if not ss_src:
    raise RuntimeError("SeedStamperAgent class not found")
OUT_SRC += rewrite_leaf_class(ss_src, "SeedStamperAgent", None) + "\n\n"

# ─── MomentFactory composite (renamed instantiations) ─────────────────

OUT_SRC += "\n# ─── PUBLIC ENTRYPOINT ────────────────────────────────────────────────\n\n"

mod, src = parse(AGENTS / COMPOSITE)
mf_class = get_class_src(mod, src, "MomentFactoryAgent")
if not mf_class:
    raise RuntimeError("MomentFactoryAgent class not found")
# Public name: MomentFactory (with MomentFactoryAgent alias below for discovery)
mf_class = re.sub(r'\bclass MomentFactoryAgent\b', 'class MomentFactory', mf_class)
# Rewrite all RENAMES
for old, new in RENAMES.items():
    mf_class = re.sub(rf'\b{re.escape(old)}\b', new, mf_class)
OUT_SRC += mf_class + "\n\n"

OUT_SRC += '''
# Alias so the brainstem's "name ends in Agent" discovery picks it up.
class MomentFactoryAgent(MomentFactory):
    pass


'''

# ─── One inlined _llm_call + _post helper (canonical from sensorium) ─

OUT_SRC += "\n# ─── Inlined LLM dispatch (one copy for the whole singleton) ──────────\n\n"

src = (AGENTS / "sensorium_agent.py").read_text()
m_llm  = re.search(r'(def _llm_call\b.*?)(?=\n(?:def |class |__manifest__|\Z))', src, re.DOTALL)
m_post = re.search(r'(def _post\b.*?)(?=\n(?:def |class |__manifest__|\Z))',     src, re.DOTALL)
if not (m_llm and m_post):
    raise RuntimeError("could not extract _llm_call/_post from sensorium_agent.py")
OUT_SRC += m_llm.group(1).rstrip() + "\n\n\n"
OUT_SRC += m_post.group(1).rstrip() + "\n"


# ─── Write ────────────────────────────────────────────────────────────

OUT.write_text(OUT_SRC)
n_lines = len(OUT_SRC.split("\n"))
n_chars = len(OUT_SRC)
print(f"  ✓ wrote {OUT}")
print(f"    {n_lines} lines, {n_chars:,} chars")
print(f"    7 internal personas + 1 public MomentFactory + MomentFactoryAgent alias")
